\set ON_ERROR_STOP on
begin;
create schema test;
create function test.ok(condition boolean,label text) returns void language plpgsql as $$ begin if condition is distinct from true then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end $$;
create function test.fails(statement text,label text) returns void language plpgsql as $$ begin begin execute statement; exception when others then raise notice 'PASS (rejected): % [%]',label,sqlerrm;return;end;raise exception 'FAIL (accepted): %',label;end $$;
grant usage on schema test to authenticated,anon;
grant execute on all functions in schema test to authenticated,anon;
insert into auth.users(id) values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222'),('33333333-3333-4333-8333-333333333333');
set local role authenticated;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
do $$
declare h uuid; foreign_h uuid; foreign_a uuid; bank uuid; saving uuid; card uuid; cash uuid; salary uuid; dining uuid; food uuid; eq uuid; tid uuid; opening uuid; invite uuid; old_version timestamptz; lines jsonb; snapshot jsonb; result text; n int;
begin
 h:=public.create_household('테스트 가계부');
 perform test.ok((select count(*)=24 from public.accounts where household_id=h),'24 default accounts seeded');
 select id into bank from public.accounts where household_id=h and name='은행';
 perform public.save_account(h,'국민은행','ASSET',null,null,bank);
 saving:=public.save_account(h,'적금','ASSET');
 select id into card from public.accounts where household_id=h and name='신용카드';
 perform public.save_account(h,'신한카드','LIABILITY',null,null,card);
 select id into cash from public.accounts where household_id=h and name='현금';
 select id into salary from public.accounts where household_id=h and name='급여';
 select id into dining from public.accounts where household_id=h and name='외식';
 select id into food from public.accounts where household_id=h and name='식비';
 select id into eq from public.accounts where household_id=h and is_system;
 opening:=public.create_opening(h,'2026-10-01',jsonb_build_array(jsonb_build_object('account_id',bank,'amount','4000000'),jsonb_build_object('account_id',saving,'amount','10000000'),jsonb_build_object('account_id',card,'amount','500000')));
 set constraints all immediate; set constraints all deferred;
 perform test.ok((select sum(case when account_type='ASSET' then balance::numeric when account_type='LIABILITY' then -balance::numeric else 0 end)=13500000 from public.account_balances where household_id=h),'opening net worth = 13,500,000');
 perform test.fails(format('select public.create_opening(%L,%L,%L)',h,'2026-10-01',jsonb_build_array(jsonb_build_object('account_id',bank,'amount','1'))),'duplicate opening rejected');
 -- 1. Salary
 tid:=public.create_transaction(h,'2026-10-02','급여',jsonb_build_array(jsonb_build_object('account_id',bank,'entry_type','DEBIT','amount','4000000'),jsonb_build_object('account_id',salary,'entry_type','CREDIT','amount','4000000')));
 set constraints all immediate; set constraints all deferred;
 perform test.ok((select balance::numeric=8000000 from public.account_balances where account_id=bank),'step 1 bank 8,000,000');
 perform test.ok((select sum(case when account_type='ASSET' then balance::numeric when account_type='LIABILITY' then -balance::numeric else 0 end)=17500000 from public.account_balances where household_id=h),'step 1 net worth 17,500,000');
 -- 2. Card expense
 tid:=public.create_transaction(h,'2026-10-03','외식',jsonb_build_array(jsonb_build_object('account_id',dining,'entry_type','DEBIT','amount','50000'),jsonb_build_object('account_id',card,'entry_type','CREDIT','amount','50000')));
 set constraints all immediate; set constraints all deferred;
 perform test.ok((select balance::numeric=550000 from public.account_balances where account_id=card),'step 2 card 550,000');
 perform test.ok((select sum(case when account_type='ASSET' then balance::numeric when account_type='LIABILITY' then -balance::numeric else 0 end)=17450000 from public.account_balances where household_id=h),'step 2 net worth 17,450,000');
 -- 3. Transfer
 tid:=public.create_transaction(h,'2026-10-04','계좌이체',jsonb_build_array(jsonb_build_object('account_id',saving,'entry_type','DEBIT','amount','1000000'),jsonb_build_object('account_id',bank,'entry_type','CREDIT','amount','1000000')));
 set constraints all immediate; set constraints all deferred;
 perform test.ok((select balance::numeric=7000000 from public.account_balances where account_id=bank) and (select balance::numeric=11000000 from public.account_balances where account_id=saving),'step 3 transfer bank 7M savings 11M');
 perform test.ok((select sum(balance::numeric)=50000 from public.account_balances where household_id=h and account_type='EXPENSE'),'step 3 transfer excluded from expenses');
 -- 4. Card repayment
 tid:=public.create_transaction(h,'2026-10-05','카드대금',jsonb_build_array(jsonb_build_object('account_id',card,'entry_type','DEBIT','amount','500000'),jsonb_build_object('account_id',bank,'entry_type','CREDIT','amount','500000')));
 set constraints all immediate; set constraints all deferred;
 perform test.ok((select balance::numeric=6500000 from public.account_balances where account_id=bank) and (select balance::numeric=50000 from public.account_balances where account_id=card),'step 4 bank 6.5M card 50,000');
 perform test.ok((select sum(balance::numeric)=50000 from public.account_balances where household_id=h and account_type='EXPENSE'),'step 4 card repayment excluded from expenses');
 -- 5. Cash expense; zero initial cash intentionally becomes negative.
 tid:=public.create_transaction(h,'2026-10-06','현금 식비',jsonb_build_array(jsonb_build_object('account_id',food,'entry_type','DEBIT','amount','20000'),jsonb_build_object('account_id',cash,'entry_type','CREDIT','amount','20000')));
 set constraints all immediate; set constraints all deferred;
 perform test.ok((select balance::numeric=-20000 from public.account_balances where account_id=cash),'step 5 cash -20,000');
 perform test.ok((select sum(balance::numeric)=17480000 from public.account_balances where household_id=h and account_type='ASSET'),'final assets 17,480,000');
 perform test.ok((select sum(balance::numeric)=50000 from public.account_balances where household_id=h and account_type='LIABILITY'),'final liabilities 50,000');
 perform test.ok((select sum(case when account_type='ASSET' then balance::numeric when account_type='LIABILITY' then -balance::numeric else 0 end)=17430000 from public.account_balances where household_id=h),'final net worth 17,430,000');
 perform test.ok((select sum(balance::numeric)=4000000 from public.account_balances where household_id=h and account_type='INCOME'),'monthly income 4,000,000');
 perform test.ok((select sum(balance::numeric)=70000 from public.account_balances where household_id=h and account_type='EXPENSE'),'monthly expenses 70,000');
 perform test.ok(not exists(select transaction_id from public.transaction_lines group by transaction_id having sum(case when entry_type='DEBIT' then amount::numeric else -amount::numeric end)<>0),'all transaction debit/credit balanced');
 snapshot:=public.ledger_snapshot(h);
 perform test.ok(jsonb_typeof(snapshot->'transactions'->0->'lines'->0->'amount')='string','BIGINT JSON serialized as strings');
 lines:=jsonb_build_array(jsonb_build_object('account_id',food,'entry_type','DEBIT','amount','30000'),jsonb_build_object('account_id',cash,'entry_type','CREDIT','amount','30000'));
 select updated_at into old_version from public.transactions where id=tid;
 perform public.update_transaction(tid,'2026-10-06','수정 식비',lines,old_version);
 set constraints all immediate; set constraints all deferred;
 perform test.ok((select balance::numeric=-30000 from public.account_balances where account_id=cash),'atomic update replaces lines');
 perform test.fails(format('select public.update_transaction(%L,%L,%L,%L,%L)',tid,'2026-10-06','stale',lines,old_version),'stale update rejected');
 select updated_at into old_version from public.transactions where id=tid;
 perform public.delete_transaction(tid,old_version);
 set constraints all immediate; set constraints all deferred;
 perform test.ok((select balance::numeric=0 from public.account_balances where account_id=cash),'deletion restores derived balance');
 perform test.fails(format('select public.create_transaction(%L,%L,%L,%L)',h,'2026-10-06','bad',jsonb_build_array(jsonb_build_object('account_id',food,'entry_type','DEBIT','amount','1'),jsonb_build_object('account_id',cash,'entry_type','CREDIT','amount','2'))),'unbalanced transaction rejected');
 perform test.fails(format('select public.create_transaction(%L,%L,%L,%L)',h,'2026-10-06','zero',jsonb_build_array(jsonb_build_object('account_id',food,'entry_type','DEBIT','amount','0'),jsonb_build_object('account_id',cash,'entry_type','CREDIT','amount','0'))),'zero rejected');
 perform test.fails(format('select public.create_transaction(%L,%L,%L,%L)',h,'2026-10-06','fraction',jsonb_build_array(jsonb_build_object('account_id',food,'entry_type','DEBIT','amount','1.5'),jsonb_build_object('account_id',cash,'entry_type','CREDIT','amount','1.5'))),'fraction rejected');
 perform test.fails(format('insert into public.transactions(household_id,transaction_date,description,created_by) values(%L,current_date,%L,auth.uid())',h,'direct insert'),'direct transactions INSERT denied');
 perform test.fails(format('delete from public.transaction_lines where account_id=%L',bank),'direct lines DELETE denied');
 perform test.fails(format('select public.save_account(%L,%L,%L,%L,null,%L)',h,'식비','EXPENSE',dining,food),'account cycle rejected');
 perform test.fails(format('select public.save_account(%L,%L,%L,null,null,%L)',h,'은행','LIABILITY',bank),'account type mutation rejected');
 perform public.save_budget(h,food,2026,10,'600000');
 perform test.ok((with recursive subtree as (select id from public.accounts where id=food union all select a.id from public.accounts a join subtree s on a.parent_account_id=s.id) select sum(l.amount)=50000 from public.transaction_lines l join subtree s on s.id=l.account_id join public.transactions t on t.id=l.transaction_id where t.transaction_date between '2026-10-01' and '2026-10-31' and l.entry_type='DEBIT'),'parent budget includes child expense');
 perform test.fails(format('select public.save_budget(%L,%L,2026,10,%L)',h,bank,'100'),'non-expense budget rejected');

 -- Failure after transaction INSERT must still roll back the entire RPC.
 select count(*) into n from public.transactions where household_id=h;
 perform test.fails(format('select public.create_transaction(%L,%L,%L,%L)',h,'2026-10-07','long memo',jsonb_build_array(jsonb_build_object('account_id',food,'entry_type','DEBIT','amount','1','memo',repeat('x',2001)),jsonb_build_object('account_id',cash,'entry_type','CREDIT','amount','1'))),'line insert failure rolls back RPC');
 perform test.ok((select count(*)=n from public.transactions where household_id=h),'no orphan transaction after failed line insert');
 lines:=jsonb_build_array(jsonb_build_object('account_id',bank,'entry_type','DEBIT','amount','9007199254740993'),jsonb_build_object('account_id',eq,'entry_type','CREDIT','amount','9007199254740993'));
 tid:=public.create_transaction(h,'2026-10-07','large integer',lines);
 set constraints all immediate; set constraints all deferred;
 perform test.ok(exists(select 1 from jsonb_array_elements(public.ledger_snapshot(h)->'transactions') t cross join lateral jsonb_array_elements(t->'lines') l where t->>'id'=tid::text and l->>'amount'='9007199254740993'),'DB JSON preserves values above JS safe integer');
 perform test.fails(format('select public.create_transaction(%L,%L,%L,%L,null,%L)',h,'2026-10-07','duplicate',lines,tid),'duplicate request ID rejected');
 select updated_at into old_version from public.transactions where id=tid;
 perform public.delete_transaction(tid,old_version);
 lines:=jsonb_build_array(jsonb_build_object('account_id',food,'entry_type','DEBIT','amount','30000'),jsonb_build_object('account_id',cash,'entry_type','CREDIT','amount','30000'));
 -- A second tenant cannot see or manipulate first tenant data.
 perform set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
 foreign_h:=public.create_household('다른 집');
 select id into foreign_a from public.accounts where household_id=foreign_h and name='현금';
 perform test.ok((select count(*)=0 from public.accounts where household_id=h),'RLS other household accounts invisible');
 perform test.ok((select count(*)=0 from public.transactions where household_id=h),'RLS other household transactions invisible');
 perform test.ok((select count(*)=0 from public.transaction_lines),'RLS transaction lines invisible');
 perform test.ok((select count(*)=0 from public.budgets where household_id=h),'RLS budgets invisible');
 perform test.ok((select count(*)=0 from public.account_balances where household_id=h),'security invoker balance view isolation');
 perform test.ok(jsonb_array_length(public.ledger_snapshot(h)->'accounts')=0,'snapshot respects RLS');
 perform test.fails(format('select public.create_transaction(%L,%L,%L,%L)',h,'2026-10-07','attack',lines),'RPC cross-tenant household rejected');
 perform test.fails(format('select public.delete_transaction(%L,now())',opening),'RPC other transaction ID rejected');
 perform set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
 perform test.fails(format('select public.create_transaction(%L,%L,%L,%L)',h,'2026-10-07','foreign account',jsonb_build_array(jsonb_build_object('account_id',food,'entry_type','DEBIT','amount','1'),jsonb_build_object('account_id',foreign_a,'entry_type','CREDIT','amount','1'))),'cross-tenant account injection rejected');
 invite:=public.create_invite(h);
 perform set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
 perform public.accept_invite(invite);
 perform test.ok((select count(*)=2 from public.household_members where household_id=h),'second member joined');
 perform public.save_budget(h,food,2026,10,'700000');
 tid:=public.create_transaction(h,'2026-10-08','구성원 거래',lines);
 select updated_at into old_version from public.transactions where id=tid;
 perform public.update_transaction(tid,'2026-10-08','구성원 수정',lines,old_version);
 select updated_at into old_version from public.transactions where id=tid;
 perform test.fails(format('select public.delete_transaction(%L,%L)',tid,old_version),'member cannot delete');
 perform test.fails(format('select public.save_account(%L,%L,%L)',h,'unauthorized','ASSET'),'member cannot manage accounts');
 perform test.fails(format('select public.rename_household(%L,%L)',h,'attack'),'member cannot rename household');
 perform test.fails(format('select public.create_invite(%L)',h),'member cannot invite');
 perform set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',true);
 perform test.fails(format('select public.accept_invite(%L)',invite),'third user cannot reuse invite');
 perform set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
 perform test.fails(format('select public.create_invite(%L)',h),'owner cannot invite third member');
 perform public.remove_member(h,'22222222-2222-4222-8222-222222222222');
 perform set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
 perform test.ok((select count(*)=0 from public.transactions where household_id=h),'removed member loses access');
 perform test.fails(format('select public.create_transaction(%L,%L,%L,%L)',h,'2026-10-09','removed',lines),'removed member cannot write');
 perform set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
 perform public.save_account(h,'현금','ASSET',null,null,cash,true);
 perform test.fails(format('select public.create_transaction(%L,%L,%L,%L)',h,'2026-10-09','archive',lines),'archived account rejected');
 set constraints all immediate;
end $$;
set local role anon;
select test.fails('select * from public.households','anonymous table read denied');
select test.fails('select public.create_household(''anon'')','anonymous RPC denied');
reset role;
-- Even privileged accidental writes cannot leave an unbalanced journal.
select test.fails($sql$do $body$ declare h uuid;t uuid;begin select id into h from public.households limit 1;insert into public.transactions(household_id,transaction_date,description,created_by) values(h,current_date,'empty','11111111-1111-4111-8111-111111111111') returning id into t;set constraints all immediate;end $body$$sql$,'constraint rejects empty journal');
rollback;
