\set ON_ERROR_STOP on
begin;
create schema fixed_test;
create function fixed_test.ok(v boolean,label text) returns void language plpgsql as $$ begin if v is distinct from true then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end $$;
create function fixed_test.reject(q text,label text) returns void language plpgsql as $$ begin begin execute q; exception when others then raise notice 'PASS rejected: % [%]',label,sqlerrm; return; end; raise exception 'FAIL accepted: %',label; end $$;
grant usage on schema fixed_test to authenticated,anon;
grant execute on all functions in schema fixed_test to authenticated,anon;
insert into auth.users values('88888888-8888-4888-8888-888888888888'),('99999999-9999-4999-8999-999999999999'),('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
set local role authenticated;
select set_config('request.jwt.claim.sub','88888888-8888-4888-8888-888888888888',true);
do $$ declare h uuid; other_h uuid; bank uuid; expense uuid; f uuid:=gen_random_uuid(); f2 uuid:=gen_random_uuid(); t uuid; token uuid; v timestamptz; deleted timestamptz; m date:=date_trunc('month',now() at time zone 'Asia/Seoul')::date; prev date; next date; n int;
begin
 prev:=(m-interval '1 month')::date;next:=(m+interval '1 month')::date;
 h:=public.create_household('고정지출 테스트');
 select id into bank from public.accounts where household_id=h and name='은행';select id into expense from public.accounts where household_id=h and name='외식';
 perform public.save_fixed_expense(h,f,0,prev,'요금','50000',31,expense,bank);
 perform fixed_test.ok((select count(*)=0 from public.transactions where household_id=h),'creating rule never creates transactions');
 perform public.save_fixed_expense(h,f,1,m,'요금','60000',31,expense,bank);
 perform fixed_test.ok((select count(*)=2 from public.fixed_expense_rules where fixed_id=f),'month versions preserved');
 perform fixed_test.ok((select amount=50000 from public.fixed_expense_rules where fixed_id=f and effective_month=prev),'previous month amount retained');
 perform fixed_test.reject(format('select public.save_fixed_expense(%L,%L,1,%L,%L,%L,31,%L,%L)',h,f,m,'stale','60000',expense,bank),'stale rule rejected');
 perform fixed_test.reject(format('select public.save_fixed_expense(%L,%L,2,%L,%L,%L,31,%L,%L)',h,f,prev,'past','60000',expense,bank),'past rule rewrite rejected');
 perform fixed_test.reject(format('select public.save_fixed_expense(%L,%L,0,%L,%L,%L,32,%L,%L)',h,gen_random_uuid(),m,'invalid','1',expense,bank),'invalid due day');
 perform fixed_test.reject(format('select public.save_fixed_expense(%L,%L,0,%L,%L,%L,1,%L,%L)',h,gen_random_uuid(),m,'invalid','9223372036854775808',expense,bank),'overflow amount');
 perform fixed_test.reject(format('select public.save_fixed_expense(%L,%L,0,%L,%L,%L,1,%L,%L)',h,gen_random_uuid(),m,'invalid','1',bank,expense),'wrong account types');
 t:=public.process_fixed_expense(h,f,m,2,0,'pay','2020-01-01','55000');
 set constraints all immediate;set constraints all deferred;
 perform fixed_test.ok((select count(*)=1 from public.transactions where household_id=h),'one actual transaction created');
 perform fixed_test.ok((select balance::bigint=-55000 from public.account_balances where account_id=bank),'actual bank balance updated');
 perform fixed_test.ok((select balance::bigint=55000 from public.account_balances where account_id=expense),'actual expense not estimate');
 perform fixed_test.ok((select count(*)=1 from public.transaction_history where transaction_id=t and action='CREATE'),'normal transaction history created');
 perform fixed_test.ok((select snapshot->>'amount'='60000' and (snapshot->>'due_date')::date=(m+interval '1 month - 1 day')::date from public.fixed_expense_records where fixed_id=f and month=m),'expected snapshot and month end');
 perform fixed_test.reject(format('select public.process_fixed_expense(%L,%L,%L,2,0,%L,%L,%L)',h,f,m,'pay','2020-01-01','55000'),'duplicate request rejected');
 perform fixed_test.reject(format('select public.process_fixed_expense(%L,%L,%L,2,1,%L,%L,%L)',h,f,m,'pay','2020-01-01','55000'),'already settled record rejected');
 perform public.save_fixed_expense(h,f2,0,m,'별도요금','1000',1,expense,bank);
 perform fixed_test.reject(format('select public.process_fixed_expense(%L,%L,%L,1,0,%L,null,null,%L)',h,f2,m,'link',t),'one transaction cannot settle two items');
 perform public.process_fixed_expense(h,f,m,2,1,'reset');
 perform fixed_test.ok((select count(*)=1 from public.transactions where household_id=h),'reset retains ledger transaction');
 perform public.process_fixed_expense(h,f,m,2,2,'link',null,null,t);
 perform fixed_test.ok((select count(*)=1 from public.transactions where household_id=h),'link does not duplicate transaction');
 select updated_at into v from public.transactions where id=t;perform public.delete_transaction(t,v);
 perform fixed_test.ok((select transaction_id=t from public.fixed_expense_records where fixed_id=f and month=m),'delete keeps linked identity');
 perform fixed_test.ok((select count(*)=0 from public.transactions where household_id=h),'deleted transaction removed from actual ledger');
 select deleted_at into deleted from public.transaction_trash where transaction_id=t;perform public.restore_transaction(t,deleted);
 perform fixed_test.ok((select count(*)=1 from public.transactions where id=t),'restore recovers original linked transaction');
 perform public.process_fixed_expense(h,f,next,2,0,'skip');
 perform fixed_test.ok((select skipped from public.fixed_expense_records where fixed_id=f and month=next),'skip only chosen month');
 perform public.process_fixed_expense(h,f,next,2,1,'reset');
 perform fixed_test.ok((select not skipped and transaction_id is null from public.fixed_expense_records where fixed_id=f and month=next),'skip reset returns pending');
 perform fixed_test.reject(format('select public.process_fixed_expense(%L,%L,%L,2,2,%L,%L,%L)',h,f,next,'pay','2199-12-31','50000'),'future actual payment rejected');
 perform fixed_test.reject(format('select public.process_fixed_expense(%L,%L,%L,1,0,%L,%L,%L)',h,f2,m,'pay','2020-01-01','-1'),'negative actual rejected');
 perform fixed_test.reject(format('select public.process_fixed_expense(%L,%L,%L,1,0,%L,%L,%L)',h,f2,m,'pay','2020-01-01','1.5'),'decimal actual rejected');
 perform public.save_account(h,'외식','EXPENSE',null,null,expense,true);
 perform fixed_test.reject(format('select public.process_fixed_expense(%L,%L,%L,1,0,%L,%L,%L)',h,f2,m,'pay','2020-01-01','1000'),'archived account rejects pay');
 perform fixed_test.ok((select count(*)=0 from public.fixed_expense_records where fixed_id=f2),'failed pay leaves no occurrence');
 perform fixed_test.ok((select count(*)=1 from public.transactions where household_id=h),'failed pay leaves no extra transaction');
 perform public.save_account(h,'외식','EXPENSE',null,null,expense,false);
 perform public.save_fixed_expense(h,f,2,next,'요금','70000',25,expense,bank,null,false);
 perform fixed_test.ok((select snapshot->>'amount'='60000' from public.fixed_expense_records where fixed_id=f and month=m),'future change does not rewrite settled snapshot');
 perform fixed_test.reject(format('select public.process_fixed_expense(%L,%L,%L,3,0,%L)',h,f,(next+interval '1 month')::date,'skip'),'stopped month rejected');
 perform fixed_test.reject(format('update public.fixed_expenses set revision=99 where id=%L',f),'direct writes denied');
 token:=public.create_invite(h);perform set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999999',true);perform public.accept_invite(token);
 perform public.process_fixed_expense(h,f2,m,1,0,'skip');
 perform fixed_test.ok(jsonb_array_length(public.fixed_expense_snapshot(h,m)->'templates')=2,'member can read and process');
 perform set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);other_h:=public.create_household('외부');
 perform fixed_test.ok(public.fixed_expense_snapshot(h,m)->'templates'='[]'::jsonb and public.fixed_expense_snapshot(h,m)->'linked_transactions'='[]'::jsonb,'outsider reads isolated');
 perform fixed_test.reject(format('select public.process_fixed_expense(%L,%L,%L,1,1,%L)',h,f2,m,'reset'),'outsider processing denied');
 perform fixed_test.reject(format('select public.save_fixed_expense(%L,%L,3,%L,%L,%L,1,%L,%L)',other_h,f,m,'hijack','1',expense,bank),'foreign template or accounts rejected');
end $$;
set local role anon;
select fixed_test.reject('select public.fixed_expense_snapshot(gen_random_uuid(),current_date)','anonymous read denied');
select fixed_test.reject('select public.process_fixed_expense(gen_random_uuid(),gen_random_uuid(),current_date,1,0,''skip'')','anonymous write denied');
rollback;
